# ~/.config/alacritty/tack.toml
[general]
  import = [ "~/.config/alacritty/alacritty.toml" ]

[colors.primary]
  background = "#1b201b" # subtle green tint
  foreground = "#b3b3b3" # dimmer than base to calm text on this bg
