-- Resolve the active theme's palette from $THEME, the runtime dial set in
-- .zshenv (nvim inherits it from the shell). Consumers keep the stable
-- `require 'theme_palette'`; this returns the committed per-theme module
-- themes/<theme>.lua (generated by theme-gen). Falls back to the default when
-- $THEME is unset (e.g. nvim launched outside a themed shell).
return require('themes.' .. (vim.env.THEME or 'vscode-dark-modern'))
